server:
  port: 8082

spring:
  datasource:
#    url: jdbc:mysql://custommysql:3306/user_service?useTimezone=true&serverTimezone=UTC
#    username: root
#    password: 1998Bursa
#    url: jdbc:mysql://demo-app-mysql:${DB_PORT:3306}/${DB_NAME}
#    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/user_service
    username: springstudent
    password: springstudent
  #    username: ${DB_USER}
#    password: ${DB_PASSWORD}
  jpa:
    properties:
        jakarta:
          persistence:
            validation:
              mode: none
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.MySQL5Dialect

    open-in-view: false
  main:
    banner-mode: off
  application:
    name: user-service

client:
  feign:
    microServiceRegister-service:
      path: http://localhost:8090/registerservice
      ready: /ready
      stopped: /stopped

    email-service:
      path: http://localhost:8085/email
      emailValidator: /validator
      activateUser: /activate
      passwordForget: /password/forget
      passwordChangeCode: /password/change/code

    token-service:
      path: http://localhost:8079/token
      extractUsername: /extract/username

app:
  routesController:
    controllers:
      userServiceController: /user
      balanceServiceController: /user/balance
    requestMapping:
      secure:
        user-service:
          getSeller: /get
          addAddressInfo: /address/add
          passwordChange: /password/change
          extractRole: /extract/role
          validateUserEmail: /activate
          activateSellerByAdmin: /activate
          addPhoto: /photo/add
          getPhoto: /photo/get

        balance-service:
          addBalance: /addbalance
          getBalance: /getbalance

      notSecure:
        user-service:
          extractSellerName: /extract/name
          registerSeller: /register-seller
          findByUsername: /find-with-username #tokenservice
          registerUser: /register-user
          passwordForget: /password/forget
          passwordChangeWithCode: /password/change-with-code

