server:
  port: 8082

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/user_service
    username: springstudent
    password: springstudent
  jpa:
    properties:
      javax:
        persistence:
          validation:
            mode: none
    hibernate:
      ddl-auto: update
    open-in-view: false
  main:
    banner-mode: off
  application:
    name: user-service
app:
  routesMicroservices:
    paymentService:
      createBalance: http://localhost:8078/paymentservice/createbalance
  routesController:
    requestmapping:
      userServiceController: /userservice
    notlocked:
      user:
        findByUsername: /findbyusername
        registerUser: /registeruser